# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import em4
import conframtion



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.se = ""
        self.pe = ""
        self.typ = ""
        self.MainWindow=MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Naglaa/Desktop/49-496199_icons-envelope-computer-mail-message-email-email-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 331, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 70, 331, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 561, 201))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 322, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsign_out = QtWidgets.QAction(MainWindow)
        self.actionsign_out.setObjectName("actionsign_out")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menufile.addAction(self.actionsign_out)
        self.menufile.addAction(self.actionexit)
        self.menubar.addAction(self.menufile.menuAction())
        self.actionsign_out.triggered.connect(self.sig1)
        self.pushButton.clicked.connect(self.co)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "email"))
        self.label.setText(_translate("MainWindow", "to:"))
        self.label_2.setText(_translate("MainWindow", "subjact:"))
        self.pushButton.setText(_translate("MainWindow", "send"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsign_out.setText(_translate("MainWindow", "sign out"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
    def sig1(self):
        self.MainWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = em4.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def co(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = conframtion.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        self.ui.sender2 = self.se
        self.ui.reciver = self.lineEdit.text()
        self.ui.content = self.textEdit.toPlainText()
        self.ui.type = self.typ
        self.ui.password = self.pe
        self.ui.subj = self.lineEdit_2.text()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
